spring:
  application:
    name: product
  data:
    mongodb:
      uri: mongodb+srv://${mongodb.username}:${mongodb.password}@shopping.55bowbl.mongodb.net/Shopping
  jpa:
    show-sql: true

jwt:
  secret: ${jwt.sec}
  expiry:
    minutes: 90

mongodb:
  username: ${mongo.user}
  password: ${mongo.pass}